In [36]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [37]:
x = np.array([[1, 2, 3], [2, 3, 4]])

print(x.shape)

(2, 3)


In [38]:
Wa = np.array([[1], [2], [1]])
Wi = np.array([[2], [1], [1]])
Wf = np.array([[2], [2], [2]])
Wo = np.array([[2], [1], [2]])

Ua = np.array([[1]])
Ui = np.array([[2]])
Uf = np.array([[2]])
Uo = np.array([[2]])

Ba = np.array([[1]])
Bi = np.array([[0]])
Bf = np.array([[1]])
Bo = np.array([[2]])


In [50]:
output_prev = np.array([[0], [0]])
c_prev = np.array([[0], [0]])

a = np.empty((2,))

for t in range(2):
    a = np.tanh((x @ Wa) + (output_prev @ Ua) + Ba)
    i = sigmoid((x @ Wi) + (output_prev @ Ua) + Bi)
    f = sigmoid((x @ Wf) + (output_prev @ Ua) + Bf)
    o = sigmoid((x @ Wo) + (output_prev @ Ua) + Bo)
    state = a * i + f * output_prev



[[0.99999997]
 [1.        ]]
[[0.99908895]
 [0.9999833 ]]
[[0.99999774]
 [0.99999999]]
[[0.99999386]
 [0.99999996]]
[[0.99908892]
 [0.9999833 ]]
[[0.99999997]
 [1.        ]]
[[0.99908895]
 [0.9999833 ]]
[[0.99999774]
 [0.99999999]]
[[0.99999386]
 [0.99999996]]
[[0.99908892]
 [0.9999833 ]]
